### ISSUE TITLE
Running the docker image container instructions

### ISSUE THREAD

**Issue by compor** [KULeuven-MICAS/snax-mlir#378]
Hey guys,

I want to run [this](https://github.com/KULeuven-MICAS/snax-mlir?tab=readme-ov-file#getting-the-container-remotely) part of the instructions as described in the README, however, I run to a few issues:

1) there's no `simple_mult` in the `kernels` dir, the simplest kernel I see is `simple_copy`. Is that the new variant? (I didn't try to look too hard into the git log for changes :-)

2) I am unsure what kind of version to use to run

```sh
sudo docker run -itv `pwd`:/repo:z ghcr.io/kuleuven-micas/snax:<insert version here>
```

When I look at ghcr.io, there doesn't seem to be a `latest` version tag or a version manifest.
The GitHub version advised to be picked up from the workflow file as is ATM is not evident to me:

```yml
name: Build and run kernels
[...]
jobs:
  build-and-run-kernels:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v3
      - uses: prefix-dev/setup-pixi@v0.8.1
        with:
          cache: true
          cache-write: ${{ github.event_name == 'push' && github.ref_name == 'main' }}
      - name: Build and run kernels
        run: pixi run snakemake -k -p -j `nproc` all
        working-directory: kernels/${{ matrix.kernel }}
    strategy:
      matrix:
[...]
```

Any direction would be appreciated, and happy to update the README ofc :-D

Maybe this is related to switching to pixi at some point?
